blank_issues_enabled: false

contact_links:
  - name: Report a security vulnerability
    url: https://github.com/rtCamp/rt-carousel/security/policy
    about: Please use GitHub Security Advisories to privately report vulnerabilities
